# Basic information setup
homeassistant: !include general/homeassistant.yaml

# Zones allow you to specify certain regions on earth (for now)
zone: !include general/zones.yaml

# Text-to-Speech (TTS) enables Home Assistant to speak to you
tts: !include general/text2speech.yaml

# The panel_iframe support allows you to add additional panels to your Home Assistant frontend
panel_iframe: !include general/panel_iframe.yaml

###  Devices  ###
#alarm_control_panel: !include alarm_control_panel.yaml
#alexa: !include alexa.yaml
automation:  !include_dir_merge_list automations/
#binary_sensor: !include binary_sensors.yaml
#camera: !include cameras.yaml
#device_tracker: !include device_trackers.yaml
group: !include_dir_merge_named groups/
#input_boolean: !include input_boolean.yaml
#input_select: !include input_select.yaml
#light: !include lights.yaml
#media_player: !include media_players.yaml
#notify: !include notify.yaml
#scene: !include scenes.yaml
script: !include_dir_merge_named scripts/
sensor:  !include_dir_merge_list sensors/
#shell_command: !include shell_commands.yaml
#switch: !include switches.yaml

xiaomi_aqara:
  gateways:
    - key: !secret aquara_gateway_key

####################################################
#                                                  #
#                     Enables                      #
#                                                  #
####################################################
cloud:
config: # Enables configuration UI
conversation: # Allows you to issue voice commands from the frontend in enabled browsers
device_tracker: !include_dir_merge_list trackers/
discovery: # Discover some devices automatically
frontend: !include general/frontend.yaml
history: # Enables support for tracking state changes over time
logbook: # View all events in a logbook
logger:
map: # Enables a map showing the location of tracked devices
sun: # Track the sun
